baseURL = 'https://taylorbritton.me'
languageCode = 'en-us'
title = 'Taylor Britton'
theme = 'mini'

[social]
github = "https://github.com/PRDeltoid/"
linkedin = "https://www.linkedin.com/in/taylor-britton-29a170151/"

[params]
author = "Taylor Britton"
bio = "Software Engineer"
description = "My Blog"
hiddenPostSummaryInHomePage = false
copyright = "Copyright 2024 Taylor Britton"